# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-25 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='emailbillscheduler',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.EmailBill', verbose_name='Email Bill'),
        ),
        migrations.AddField(
            model_name='emailbillscheduler',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='emailbillscheduler',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_task', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AddField(
            model_name='emailbillinvoice',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.EmailBill', verbose_name='EmailBill'),
        ),
        migrations.AddField(
            model_name='emailbill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='checkoutinvoice',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.Checkout', verbose_name='Checkout'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.CatalogItem', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='buttoninvoice',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.Button', verbose_name='Button'),
        ),
        migrations.AddField(
            model_name='button',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
