# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190728_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=1000, null=True, verbose_name='email address notification'),
        ),
    ]
