# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-29 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190729_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='width',
        ),
    ]
