# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190729_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refund',
            field=models.CharField(choices=[('Current', 'Current'), ('Fixed', 'Fixed')], default='Current', max_length=30, verbose_name='refund policy'),
        ),
    ]
