# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pesaify.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_invoice_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Address')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='CryptoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_code', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='crypto_code')),
                ('payment_type', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='payment_type')),
                ('rate', models.FloatField(default=0, verbose_name='rate')),
                ('paid', models.FloatField(default=0, verbose_name='rate')),
                ('price', models.FloatField(default=0, verbose_name='rate')),
                ('due', models.FloatField(default=0, verbose_name='rate')),
                ('address', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='payment_type')),
                ('url', models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='payment_type')),
                ('total_due', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='payment_type')),
                ('network_fee', models.FloatField(default=0, verbose_name='rate')),
                ('tx_count', models.IntegerField(default=0, verbose_name='rate')),
                ('crypto_paid', models.FloatField(default=0, verbose_name='rate')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ExRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.IntegerField(default=0, verbose_name='USD')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundable', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='MinerFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='MinerFeesBTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satoshis_per_byte', models.IntegerField(default=0, verbose_name='satoshis_per_byte')),
                ('total_fee', models.IntegerField(default=0, verbose_name='total_fee')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.IntegerField(default=0, verbose_name='btc')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bip21', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='bip21')),
                ('bip72', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='bip72')),
                ('bip72_b', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='bip72_b')),
                ('bip73', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='bip73')),
                ('bolt11', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='bolt11')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportedTransactionCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportedTransactionCurrenciesBTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='city',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='address',
            new_name='bitcoin_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='expiration_date',
            new_name='expiration_time',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='monitoring_date',
            new_name='invoice_time',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notification_url',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='speed',
        ),
        migrations.AddField(
            model_name='buyer',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.FloatField(default=0, verbose_name='amount paid'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_due',
            field=models.FloatField(default=0, verbose_name='btc due'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_paid',
            field=models.FloatField(default=0, verbose_name='btc paid'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_price',
            field=models.FloatField(default=0, verbose_name='btc price'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_paid_btc_miner_fee',
            field=models.FloatField(default=0, verbose_name='Buyer paid btc miner fee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_total_btc_amount',
            field=models.FloatField(default=0, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('BTC', 'BTC - Bitcoin'), ('BCH', 'BCH - Bitcoin Cash'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Eurozone Euro'), ('GBP', 'GBP - Pound Sterling'), ('JPY', 'JPY - Japanese Yen'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar'), ('CNY', 'CNY - Chinese Yuan'), ('CHF', 'CHF - Swiss Franc'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('KRW', 'KRW - South Korean Won'), ('AED', 'AED - UAE Dirham '), ('AFN', 'AFN - Afghan Afghani '), ('ALL', 'ALL - Albanian Lek '), ('AMD', 'AMD - Armenian Dram '), ('ANG', 'ANG - Netherlands Antillean Guilder '), ('AOA', 'AOA - Angolan Kwanza '), ('ARS', 'ARS - Argentine Peso '), ('AWG', 'AWG - Aruban Florin '), ('AZN', 'AZN - Azerbaijani Manat '), ('BAM', 'BAM - Bosnia-Herzegovina Convertible Mark '), ('BBD', 'BBD - Barbadian Dollar '), ('BDT', 'BDT - Bangladeshi Taka '), ('BGN', 'BGN - Bulgarian Lev '), ('BHD', 'BHD - Bahraini Dinar '), ('BIF', 'BIF - Burundian Franc '), ('BMD', 'BMD - Bermudan Dollar '), ('BND', 'BND - Brunei Dollar '), ('BOB', 'BOB - Bolivian Boliviano '), ('BRL', 'BRL - Brazilian Real '), ('BSD', 'BSD - Bahamian Dollar '), ('BTN', 'BTN - Bhutanese Ngultrum '), ('BWP', 'BWP - Botswanan Pula '), ('BYN', 'BYN - Belarusian Ruble '), ('BZD', 'BZD - Belize Dollar '), ('CDF', 'CDF - Congolese Franc '), ('CLF', 'CLF - Chilean Unit of Account (UF) '), ('CLP', 'CLP - Chilean Peso '), ('COP', 'COP - Colombian Peso '), ('CRC', 'CRC - Costa Rican Colón '), ('CUP', 'CUP - Cuban Peso '), ('CVE', 'CVE - Cape Verdean Escudo '), ('CZK', 'CZK - Czech Koruna '), ('DJF', 'DJF - Djiboutian Franc '), ('DKK', 'DKK - Danish Krone '), ('DOP', 'DOP - Dominican Peso '), ('DZD', 'DZD - Algerian Dinar '), ('EGP', 'EGP - Egyptian Pound '), ('ETB', 'ETB - Ethiopian Birr '), ('FJD', 'FJD - Fijian Dollar '), ('FKP', 'FKP - Falkland Islands Pound '), ('GEL', 'GEL - Georgian Lari '), ('GHS', 'GHS - Ghanaian Cedi '), ('GIP', 'GIP - Gibraltar Pound '), ('GMD', 'GMD - Gambian Dalasi '), ('GNF', 'GNF - Guinean Franc '), ('GTQ', 'GTQ - Guatemalan Quetzal '), ('GUSD', 'GUSD - Gemini US Dollar '), ('GYD', 'GYD - Guyanaese Dollar '), ('HKD', 'HKD - Hong Kong Dollar '), ('HNL', 'HNL - Honduran Lempira '), ('HRK', 'HRK - Croatian Kuna '), ('HTG', 'HTG - Haitian Gourde '), ('HUF', 'HUF - Hungarian Forint '), ('IDR', 'IDR - Indonesian Rupiah '), ('ILS', 'ILS - Israeli Shekel '), ('INR', 'INR - Indian Rupee '), ('IQD', 'IQD - Iraqi Dinar '), ('IRR', 'IRR - Iranian Rial '), ('ISK', 'ISK - Icelandic Króna '), ('JEP', 'JEP - Jersey Pound '), ('JMD', 'JMD - Jamaican Dollar '), ('JOD', 'JOD - Jordanian Dinar '), ('KES', 'KES - Kenyan Shilling '), ('KGS', 'KGS - Kyrgystani Som '), ('KHR', 'KHR - Cambodian Riel '), ('KMF', 'KMF - Comorian Franc '), ('KPW', 'KPW - North Korean Won '), ('KWD', 'KWD - Kuwaiti Dinar '), ('KYD', 'KYD - Cayman Islands Dollar '), ('KZT', 'KZT - Kazakhstani Tenge '), ('LAK', 'LAK - Laotian Kip '), ('LBP', 'LBP - Lebanese Pound '), ('LKR', 'LKR - Sri Lankan Rupee '), ('LRD', 'LRD - Liberian Dollar '), ('LSL', 'LSL - Lesotho Loti '), ('LYD', 'LYD - Libyan Dinar '), ('MAD', 'MAD - Moroccan Dirham '), ('MDL', 'MDL - Moldovan Leu '), ('MGA', 'MGA - Malagasy Ariary '), ('MKD', 'MKD - Macedonian Denar '), ('MMK', 'MMK - Myanma Kyat '), ('MNT', 'MNT - Mongolian Tugrik '), ('MOP', 'MOP - Macanese Pataca '), ('MRU', 'MRU - Mauritanian Ouguiya '), ('MUR', 'MUR - Mauritian Rupee '), ('MVR', 'MVR - Maldivian Rufiyaa '), ('MWK', 'MWK - Malawian Kwacha'), ('MXN', 'MXN - Mexican Peso '), ('MYR', 'MYR - Malaysian Ringgit '), ('MZN', 'MZN - Mozambican Metical '), ('NAD', 'NAD - Namibian Dollar '), ('NGN', 'NGN - Nigerian Naira '), ('NIO', 'NIO - Nicaraguan Córdoba '), ('NOK', 'NOK - Norwegian Krone '), ('NPR', 'NPR - Nepalese Rupee '), ('OMR', 'OMR - Omani Rial '), ('PAB', 'PAB - Panamanian Balboa '), ('PEN', 'PEN - Peruvian Nuevo Sol '), ('PGK', 'PGK - Papua New Guinean Kina '), ('PHP', 'PHP - Philippine Peso '), ('PKR', 'PKR - Pakistani Rupee '), ('PLN', 'PLN - Polish Zloty '), ('PYG', 'PYG - Paraguayan Guarani '), ('QAR', 'QAR - Qatari Rial '), ('RON', 'RON - Romanian Leu '), ('RSD', 'RSD - Serbian Dinar '), ('RUB', 'RUB - Russian Ruble '), ('RWF', 'RWF - Rwandan Franc '), ('SAR', 'SAR - Saudi Riyal '), ('SBD', 'SBD - Solomon Islands Dollar '), ('SCR', 'SCR - Seychellois Rupee '), ('SDG', 'SDG - Sudanese Pound '), ('SGD', 'SGD - Singapore Dollar '), ('SHP', 'SHP - Saint Helena Pound '), ('SLL', 'SLL - Sierra Leonean Leone '), ('SOS', 'SOS - Somali Shilling '), ('SRD', 'SRD - Surinamese Dollar '), ('STN', 'STN - São Tomé and Príncipe Dobra '), ('SVC', 'SVC - Salvadoran Colón '), ('SYP', 'SYP - Syrian Pound '), ('SZL', 'SZL - Swazi Lilangeni '), ('THB', 'THB - Thai Baht '), ('TJS', 'TJS - Tajikistani Somoni '), ('TMT', 'TMT - Turkmenistani Manat '), ('TND', 'TND - Tunisian Dinar '), ('TOP', 'TOP - Tongan Paʻanga '), ('TRY', 'TRY - Turkish Lira '), ('TTD', 'TTD - Trinidad and Tobago Dollar '), ('TWD', 'TWD - New Taiwan Dollar '), ('TZS', 'TZS - Tanzanian Shilling '), ('UAH', 'UAH - Ukrainian Hryvnia '), ('UGX', 'UGX - Ugandan Shilling '), ('USDC', 'USDC - Circle USD Coin '), ('UYU', 'UYU - Uruguayan Peso '), ('UZS', 'UZS - Uzbekistan Som '), ('VEF', 'VEF - Venezuelan Bolívar Fuerte '), ('VES', 'VES - Venezuelan Bolívar Soberano '), ('VND', 'VND - Vietnamese Dong '), ('VUV', 'VUV - Vanuatu Vatu '), ('WST', 'WST - Samoan Tala '), ('XAF', 'XAF - CFA Franc BEAC '), ('XCD', 'XCD - East Caribbean Dollar '), ('XOF', 'XOF - CFA Franc BCEAO '), ('XPF', 'XPF - CFP Franc '), ('YER', 'YER - Yemeni Rial '), ('ZAR', 'ZAR - South African Rand '), ('ZMW', 'ZMW - Zambian Kwacha '), ('ZWL', 'ZWL - Zimbabwean Dollar '), ('XAG', 'XAG - Silver (troy ounce) '), ('XAU', 'XAU - Gold (troy ounce) ')], default='BTC', max_length=256, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_time',
            field=models.DateTimeField(auto_now=True, verbose_name='current Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exception_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guid',
            field=models.CharField(default=pesaify.payment.models.get_default_uuid, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_desc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='low_fee_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.FloatField(default=0, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refund_address_request_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Payment Url'),
        ),
        migrations.AddField(
            model_name='supportedtransactioncurrenciesbtc',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='supportedtransactioncurrencies',
            name='btc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.SupportedTransactionCurrenciesBTC', verbose_name='SupportedTransactionCurrenciesBTC'),
        ),
        migrations.AddField(
            model_name='supportedtransactioncurrencies',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='paymenturls',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='paymenttotals',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='payments',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='paymentcodes',
            name='btc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentUrls', verbose_name='PaymentUrls'),
        ),
        migrations.AddField(
            model_name='paymentcodes',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='minerfeesbtc',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='minerfees',
            name='btc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.MinerFeesBTC', verbose_name='MinerFeesBTC'),
        ),
        migrations.AddField(
            model_name='minerfees',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='flags',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='exrates',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='btc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.ExRates', verbose_name='ExRates'),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='ex_rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentUrls', verbose_name='PaymentUrls'),
        ),
        migrations.AddField(
            model_name='cryptoinfo',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice'),
        ),
    ]
