# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190815_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.DateTimeField(verbose_name='current Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='expiration_time',
            field=models.DateTimeField(verbose_name='expiration Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_time',
            field=models.DateTimeField(verbose_name='monitoring Date'),
        ),
    ]
