# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20190815_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='employee',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tip',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='tip'),
        ),
    ]
