# Generated by Django 2.2.4 on 2019-08-20 22:40

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import pesaify.payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0013_auto_20190816_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='catalogorder',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-current_time']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='itype',
        ),
        migrations.AddField(
            model_name='invoice',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extras',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AddField(
            model_name='invoice',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='object id'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.CharField(default=pesaify.payment.models.get_default_uuid, editable=False, max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='CatalogOrder',
        ),
    ]
