# Generated by Django 2.2.4 on 2019-08-20 22:40

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20190821_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extras',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
