# Generated by Django 2.2.4 on 2019-08-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20190821_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='extras',
            new_name='extra',
        ),
    ]
