# Generated by Django 2.2.4 on 2019-08-21 16:47

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20190821_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notify',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
