# Generated by Django 2.2.4 on 2019-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_invoice_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='employee',
        ),
        migrations.AddField(
            model_name='invoice',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=1000, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notification_url',
            field=models.URLField(blank=True, max_length=2560, verbose_name='notification url'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=2560, verbose_name='redirect url'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=1000, null=True, verbose_name='email address'),
        ),
    ]
