# Generated by Django 2.2.4 on 2019-08-21 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import pesaify.payment.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20190821_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address1',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Shipping Address 1'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address2',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Shipping Address 2'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}'), 'Only numbers are allowed in format 000-000-000-000', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='post code'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='region',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='region'),
        ),
        migrations.CreateModel(
            name='MobileMoneySettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('MM', 'Mobile Money (MM)')], default='MM', max_length=256, verbose_name='currency')),
                ('phone_number', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}|\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{3}'), 'Only numbers are allowed in format 000-000-000-000', 'invalid')], verbose_name='phone number')),
                ('country', django_countries.fields.CountryField(blank=True, countries=pesaify.payment.models.AfricaCountries, max_length=2, verbose_name='country')),
                ('label', models.CharField(default='', max_length=100, verbose_name='label')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CryptoSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('BTC', 'Bitcoin (BTC)'), ('BCH', 'Bitcash (BCH)')], default='BTC', max_length=256, verbose_name='currency')),
                ('address', models.CharField(max_length=100, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='label')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BankSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UGX', 'Uganda Shillings (UGX)'), ('KES', 'Kenya Shillings (KZS)'), ('TZS', 'Tanzania Shillings (TZS)'), ('EUR', 'European Euro (EUR)'), ('GBP', 'Pound Sterling (GBP)'), ('USD', 'US Dollar (USD)')], default='USD', max_length=256, verbose_name='currency')),
                ('name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('post_code', models.CharField(default='', max_length=256, verbose_name='post code')),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('swift_bic', models.CharField(max_length=100, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='label')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice', verbose_name='Invoice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
