#!/bin/bash

NAME="pesaify"                                              # Name of the application
DJANGODIR=/home/pesaify/pesaify-business/pesaify-business             # Django project directory
SOCKFILE=/home/pesaify/pesaify-business/run/gunicorn.sock        # we will communicte using this unix socket
USER=pesaify                                                # the user to run as
GROUP=pesaify                                               # the group to run as
NUM_WORKERS=3                                               # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=settings.local                       # which settings file should Django use
DJANGO_WSGI_MODULE=settings.wsgi                            # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/pesaify/pesaify-business/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/pesaify/pesaify-business/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
