# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'العربية\u200f'), ('ast', 'Asturiano'), ('az', 'Azərbaycan dili'), ('bg', 'Български'), ('be', 'Беларуская'), ('bn', 'বাংলা'), ('br', 'Bretón'), ('bs', 'Bosanski'), ('ca', 'Català'), ('cs', 'Čeština'), ('cy', 'Cymraeg'), ('da', 'Dansk'), ('de', 'Deutsch'), ('el', 'Ελληνικά'), ('en', 'English (US)'), ('en-au', 'English (Australia)'), ('en-gb', 'English (UK)'), ('eo', 'esperanta'), ('es', 'Español'), ('es-ar', 'Español (Argentina)'), ('es-mx', 'Español (México)'), ('es-ni', 'Español (Nicaragua)'), ('es-ve', 'Español (Venezuela)'), ('et', 'Eesti'), ('eu', 'Euskara'), ('fa', 'فارسی\u200f'), ('fi', 'Suomi'), ('fr', 'Français'), ('fy', 'Frysk'), ('ga', 'Irish'), ('gl', 'Galego'), ('he', 'עברית\u200f'), ('hi', 'हिन्दी'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('ia', 'Interlingua'), ('id', 'Bahasa Indonesia'), ('io', 'IDO'), ('is', 'Íslenska'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('kk', 'Қазақша'), ('km', 'ភាសាខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('lb', 'Lëtzebuergesch'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('mn', 'Монгол'), ('mr', 'मराठी'), ('my', 'မြန်မာ'), ('nb', 'Norsk (bokmål)'), ('ne', 'नेपाली'), ('nl', 'Nederlands'), ('nn', 'Norsk (nynorsk)'), ('os', 'Ирон æвзаг'), ('pa', 'ਪੰਜਾਬੀ'), ('pl', 'Polski'), ('pt', 'Português (Portugal)'), ('pt-br', 'Português (Brasil)'), ('ro', 'Română'), ('ru', 'Русский'), ('sk', 'Slovenčina'), ('sl', 'Slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sr-latn', 'srpski'), ('sv', 'Svenska'), ('sw', 'Kiswahili'), ('ta', 'தமிழ்'), ('te', 'తెలుగు'), ('th', 'ภาษาไทย'), ('tr', 'Türkçe'), ('tt', 'татар теле'), ('udm', 'удмурт кыл'), ('uk', 'Українська'), ('ur', 'اردو\u200f'), ('vi', 'Tiếng Việt'), ('zh-hans', '中文(简体)'), ('zh-hant', '中文(香港)')], default='en', max_length=200, verbose_name='default language'),
        ),
    ]
