# Generated by Django 2.2.1 on 2019-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190726_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='colorize_tags',
            field=models.BooleanField(blank=True, default=False, verbose_name='colorize tags'),
        ),
    ]
