# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import pesaify.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190727_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksettlement',
            name='token',
        ),
        migrations.RemoveField(
            model_name='cryptosettlement',
            name='token',
        ),
        migrations.RemoveField(
            model_name='mobilemoneysettlement',
            name='token',
        ),
        migrations.AlterField(
            model_name='banksettlement',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='banksettlement',
            name='currency',
            field=models.CharField(choices=[('UGX', 'Uganda Shillings (UGX)'), ('KES', 'Kenya Shillings (KZS)'), ('TZS', 'Tanzania Shillings (TZS)'), ('EUR', 'European Euro (EUR)'), ('GBP', 'Pound Sterling (GBP)'), ('USD', 'US Dollar (USD)')], default='USD', max_length=256, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='business',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='cryptosettlement',
            name='currency',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin (BTC)'), ('BCH', 'Bitcash (BCH)')], default='BTC', max_length=256, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='mobilemoneysettlement',
            name='country',
            field=django_countries.fields.CountryField(blank=True, countries=pesaify.users.models.AfricaCountries, max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='mobilemoneysettlement',
            name='currency',
            field=models.CharField(choices=[('MM', 'Mobile Money (MM)')], default='MM', max_length=256, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_document',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='nationality'),
        ),
    ]
