# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-29 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190728_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettlement',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='cryptosettlement',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='mobilemoneysettlement',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='token'),
        ),
    ]
