# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-01 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190729_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='speed',
        ),
    ]
