# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_business_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettlement',
            name='business',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Business', verbose_name='Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptosettlement',
            name='business',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Business', verbose_name='Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilemoneysettlement',
            name='business',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Business', verbose_name='Business'),
            preserve_default=False,
        ),
    ]
