# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190805_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='colorize_tags',
        ),
    ]
