# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-15 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_colorize_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
    ]
